SP1 US7 ST3 Foto options
BalancyTeam/balancy-app-ios pull request #4
Opened 2024-01-06 19:04 UTC by SashkaToropov

## Description

The `AddPhotoViewController` is a view controller responsible for allowing users to add photos to their profile. It provides a user interface for selecting photos from the photo library or generation photo randomly(not implemented yet). Once a photo is selected, the view controller handles the necessary operations to save the photo and update the user's profile with the new photo.

## Changes Made

1. Implemented the `PHPickerViewControllerDelegate` protocol to handle photo selection from the photo library.
2. Added a `picker(_:didFinishPicking:)` method to handle the selected photo.
3. Extracted the logic for handling the add photo button tap into a separate `addPhotoButtonTapped()` method.
4. Added the `setupAddPhotoButton()` method to set up the add photo button with the appropriate action.
5. Configured the `PHPickerConfiguration` to limit the selection to one photo and filter for images only.
6. Updated the `addPhotoButtonTapped()` method to present the `PHPickerViewController` and set its delegate.
7. Added the `nextButton` to move to the next screen after choosing the photo.
8. Added the `skipButton` to move to the next screen if a photo isn't chosen.

## Functionality

### AddPhotoButton
https://github.com/BalancyTeam/balancy-app-ios/assets/101838036/28864eda-4d1d-44c3-b3d4-b1bc264f9eda

### NextButton
https://github.com/BalancyTeam/balancy-app-ios/assets/101838036/da47df79-a630-4452-b50f-3868110b6e17

### SkipButton
https://github.com/BalancyTeam/balancy-app-ios/assets/101838036/1d947d4d-544a-4595-8c6e-64db65988db3

## Link to design on Figma

https://www.figma.com/file/gYEuVkB1IVk2xertKYyMki/Prototype?type=design&node-id=2664-20503&mode=dev

2024-01-08 01:25 UTC, pavlobilohaienko requested changes

2024-01-08 01:25 UTC, pavlobilohaienko commented on Balancyй/Balancyй/User Settings/ImagePicking/Views/AddPhotoViewController.swift
> +        present(categoryBalanceViewController, animated: false)
Any reason for making it not animated?

2024-01-08 01:25 UTC, pavlobilohaienko commented on Balancyй/Balancyй/User Settings/ImagePicking/Views/AddPhotoViewController.swift
> +        guard let selectedImage = addPhotoButton.currentImage else { return }
Just returning here when have no image selected is not enought. Make sure you disabled the next button from the start and only enable it after first image selection/generation.

Also, combine 2 bindings under the same `guard`.

2024-01-08 01:25 UTC, pavlobilohaienko commented on Balancyй/Balancyй/User Settings/ImagePicking/Views/AddPhotoViewController.swift
> +            nextButton.isEnabled = false
This is not the right logic since you do early return from this method without changing the button's state when having no image selected.

2024-01-08 01:25 UTC, pavlobilohaienko commented on Balancyй/Balancyй/User Settings/ImagePicking/Views/AddPhotoViewController.swift
> +            viewModel.saveImageToFileManager(selectedImageName, selectedImage)
This can be unconditional since you already have both the selected image and its name.

2024-01-08 01:25 UTC, pavlobilohaienko commented on Balancyй/Balancyй/User Settings/ImagePicking/Views/AddPhotoViewController.swift
> +private struct AddPhotoViewControllerProvider: PreviewProvider {
Proposal: use Macro instead.

![telegram-cloud-photo-size-2-5249465057199380691-y](https://github.com/BalancyTeam/balancy-app-ios/assets/29002649/474658ce-acfc-40be-abe0-3e5589825169)

To make this work, make the following change to the extension with preview impelmentation: 
![telegram-cloud-photo-size-2-5249465057199380692-y](https://github.com/BalancyTeam/balancy-app-ios/assets/29002649/e4760099-574f-4134-a0d5-31bacc077f8f)

2024-01-08 01:26 UTC, pavlobilohaienko commented on Balancyй/Balancyй/User Settings/ImagePicking/Views/CategoryBalanceViewController.swift
> +//  CategoryBalanceViewController.swift
This VC would not be related to the Image picking flow. Even if you just need a stub for now, create a new group for it and name it as the flow of the VC.

2024-01-08 01:30 UTC, pavlobilohaienko commented on Balancyй/Balancyй/User Settings/ImagePicking/ViewModels/AddPhotoViewModel.swift
> +class AddPhotoViewModel {
This class does nothing except for writing an image to the FileManager. It's not a view-model of any kind. 
To not be confusing, change it to something more specific, e.g. `ProfilePhotoManager`.

2024-01-08 01:43 UTC, pavlobilohaienko commented
All the buttons have no visual effent when tapping on them. Please provide the standard effect for them.

2024-01-08 18:10 UTC, SashkaToropov commented on Balancyй/Balancyй/User Settings/ImagePicking/Views/AddPhotoViewController + PHPicker.swift
> +    // MARK: - PHPickerViewControllerDelegate
The addPhotoButtonTapped method requires importing the PhotosUI framework. Is it better to create another extension in this file and put this method there or move it to VC and import PhotosUI there?

2024-01-10 18:53 UTC, SashkaToropov commented on Balancyй/Balancyй/User Settings/ImagePicking/Views/AddPhotoViewController.swift
> +        button.setTitle("Пропустити", for: .normal)
The second part of the comment is unclear to me. I don't understand where to store methods to configure components and where they must be passed to.

2024-01-12 23:50 UTC, pavlobilohaienko commented on Balancyй/Balancyй/User Settings/ImagePicking/Views/AddPhotoViewController.swift
> +        button.setTitle("Пропустити", for: .normal)
About the second comment. In general, you have 2 options for customizing UI elements:
1. Create a specific view subclass, e.g. `SkipButton` so it has the only possible title "Пропустити", and setup this title internally.
2. Create a common button and configure it as needed to make it look as the desired UI element. In this case, button doesn't know it's purpose, so you need to pass the title externally and set this value to the button.

Now, if you decide to follow the first approach, it will look similar to the existing implementation. But for the second case, the title is kind of unknown for the button initially and can probably change later. That's why we need to separate the initialization into 3 separate parts:
1. UI setup (how it looks).
2. Layout (how it's positioned and sized).
3. Setting value (what data or content it's displaying).

And only the 1 should be done in lazy init blocks, when you write `private let someView: SomeView = { ... }()`.
Whereas 2 could be written in a private method called from the viewDidLoad, where you probably setup all the constraints for the subviews. And 3 should be done from everywhere, but again in a separate method which is specifically used to fill the view with data.

2024-01-24 21:04 UTC, pavlobilohaienko approved these changes

2024-01-24 21:04 UTC, pavlobilohaienko commented on Balancyй/Balancyй/UserSettings/ImagePicking/Helpers/ProfilePhotoManager.swift
> +            for file in files {
Fix indentation.

2024-01-24 21:04 UTC, pavlobilohaienko commented on Balancyй/Balancyй/UserSettings/ImagePicking/Helpers/ProfilePhotoManager.swift
> +        guard let files = try? fileManager.contentsOfDirectory(at: path, includingPropertiesForKeys: nil) else { return }
Nope. You need to have a subdirectory, e.g. `/ProfileImage`. So you won't remove all the user files by accident.

2024-01-24 21:04 UTC, pavlobilohaienko commented on Balancyй/Balancyй/en.lproj/Localizable.strings
> +"skip" = "Пропустити";
Nope. Don't add uk localization to en file. In case you don't need a "base" localization and have only 1 locale for now, disable base in settings and only create uk file.

2024-01-24 21:27 UTC, pavlobilohaienko commented on Balancyй/Balancyй/UserSettings/ImagePicking/Helpers/ProfilePhotoManager.swift
> +        guard let files = try? fileManager.contentsOfDirectory(at: path, includingPropertiesForKeys: nil) else { return }
Nevermind.

2024-02-06 18:54 UTC, ToBiSiD approved these changes

2024-02-06 18:55 UTC, merged