sp1_us7_st2_modal_error_big_file (user avatar image error modal)
BalancyTeam/balancy-app-ios pull request #5
Opened 2024-02-04 18:20 UTC by ToBiSiD

### PR with implementation of view controller (AvatarPickerImageErrorViewController) that shows size error of selected photo  

in this pull request:
1.  Implemented **_AvatarPickerImageErrorViewController_**
2. Add **_RoundedButtonView_** as reusable view component
3. Add some methods to View and ViewController Extensions (addSubviews, setShadow)
4. Add **_ImageLoaderService_** to load image (using for test)
5. Add **_ProfileVerificationService_** to check profile data (now only avatarImage size)
6. Implement _Preview Logic_ for _UIView_ components (same as UIViewController Preview Logic)

### Trello-Task
[https://trello.com/c/invYI8bi/16-sp1-us7-st2-pop-up-error-big-file](url)

### Figma design
[https://www.figma.com/file/ZLApCUbNmEGlJ6VeW1OQEN/ios-balancуй?type=design&node-id=2403-55414&mode=design&t=PwxBOiOCk0bbqvHj-4](url)

### Screenshots

**AvatarPickerImageErrorViewController  Preview**
<img width="290" alt="Screenshot 2024-02-27 at 13 35 09" src="https://github.com/BalancyTeam/balancy-app-ios/assets/45521876/675881c2-d384-43be-8c5a-12c1d73105ab">

**RoundedButtonView Preview with custom color and border**
<img width="288" alt="Screenshot 2024-02-27 at 13 34 54" src="https://github.com/BalancyTeam/balancy-app-ios/assets/45521876/3936e248-4ea1-4461-9dd2-01dd23a3eadd">

2024-02-06 20:58 UTC, pavlobilohaienko commented
Please fix merge conflicts by making the branch up-to-date with develop.

2024-02-06 21:01 UTC, pavlobilohaienko commented
Please add screenshots/screen recordings on what AvatarPickerImageErrorViewController and RoundedButtonView look like. Also, would be nice to add preview to the `RoundedButtonView` as it's meant to be reusable.

2024-02-06 21:02 UTC, pavlobilohaienko requested changes
See comments. Add integration with other components if possible.

2024-04-02 17:41 UTC, pavlobilohaienko commented on Balancyй/Balancyй/Extensions/Int+Extensions.swift
> +    func convertToSize() -> Double {
Better keep it computed var and specify name that explains the new value meaning, e.g. `fileSizeInMegabytes`.

2024-04-02 18:02 UTC, pavlobilohaienko approved these changes
Looks good in general. Can be merged after fixing the latest comments.

2024-04-02 18:02 UTC, pavlobilohaienko commented on Balancyй/Balancyй/UserSettings/ImagePicking/Helpers/ProfileVerificationService.swift
> +    func verifyImage(_ image: PHPickerResult) -> Bool {
The method seems to be doing the following: trying to pick an image checking its size and returning a Bool to understand if the criterias for the selected image are satisfied. Probably it's better to separate 2 responsibilities of this method as follows:
1. Verify the image.
2. Set `selectedImage` in case verification was successful.
And should probably be the 2 separate methods (variables).
E.g.:
1. Check if a verificationService.isValidImage property.
2. Call the .setSelectedImage(image) in case the verification returns `true`.

2024-04-23 17:10 UTC, pavlobilohaienko approved these changes

2024-04-23 17:11 UTC, pavlobilohaienko commented on Balancyй/Balancyй/UserSettings/Reusable/BaseImageSelectionViewController.swift
> +class BaseImageSelectionViewController: UIViewController {
`final class`

2024-06-04 16:25 UTC, SashkaToropov approved these changes

2024-06-04 16:57 UTC, merged